import { PIXELS_PER_METER } from '../physics/Constants';
import * as Util from './util';

export enum GenerationShape {
    Box = 0,
    Circle,
    Regular,
    Random,
}

export enum MouseMode {
    Grab = 0,
    Force,
}

// Simulation settings
export const Settings = {
    width: 1280,
    height: 720,
    clipWidth: 1280,
    clipHeight: 720,
    paused: false,
    frequency: 60,
    GJK_MAX_ITERATION: 20,
    GJK_TOLERANCE: (1e-13 * PIXELS_PER_METER) ** 2,
    EPA_MAX_ITERATION: 20,
    EPA_TOLERANCE: 1e-13 * PIXELS_PER_METER,
    applyGravity: true,
    positionCorrection: true,
    impulseAccumulation: true,
    warmStarting: true,
    indicateCP: false,
    indicateCoM: false,
    showBoundingBox: false,
    showContactLink: false,
    mode: MouseMode.Grab,
    mouseStrength: 1.5,
    numIterations: 10,
    newBodySettings: {
        shape: GenerationShape.Box,
        density: 8 / (PIXELS_PER_METER * PIXELS_PER_METER),
        size: 0.5 * PIXELS_PER_METER,
        friction: 0.7,
        restitution: 0.0,
        numVertices: Math.trunc(Util.random(3.0, 18.0)),
        generateMultiple: false,
    },
    gravity: -10,
    gravityScale: 0.75 * PIXELS_PER_METER,
    penetrationSlop: 0.005 * PIXELS_PER_METER,
    restitutionSlop: 0.5 * PIXELS_PER_METER,
    positionCorrectionBeta: 0.2,
    warmStartingThreshold: (0.005 * PIXELS_PER_METER) ** 2,
    deadBottom: -10 * PIXELS_PER_METER,
    resetCamera: true,
    grabCenter: false,
    showInfo: false,
    randomConvexMaxVertices: 8,
    regularPolygonMaxVertices: 11,
    defaultDensity: 12.5 / 1000 / (PIXELS_PER_METER * PIXELS_PER_METER),
    defaultFriction: 0.7,
    defaultRestitution: 0.0,
    blockSolve: true,
    colorizeBody: false,
    colorizeIsland: false,
    restLinearTolerance: (0.005 * PIXELS_PER_METER) ** 2,
    restAngularTolerance: ((0.5 * Math.PI) / 180.0) ** 2,
    sleepingWait: 0.5,
    colorizeActiveBody: true,
    sleepEnabled: true,
    applyWarmStartingThreshold: true,
    showProfile: false,
    visualizeAABBTree: false,
};
